Repository Vacasa/python-vacasa-connect-sdk, pull requests merged in 2020-07, with the labels that each got.

#96 Feature/unit blocks
  CHANGELOG.md
  setup.py
  vacasa/connect/connect.py
Labels: version/minor

#100 Feature/unit blocks
  CHANGELOG.md
  setup.py
  vacasa/connect/connect.py
Labels: version/patch

#103 TRAP-191 Fix update reservation buffer
  CHANGELOG.md
  setup.py
  vacasa/connect/connect.py
Labels: security
